In [2]:
import pandas as pd
import numpy as np
Energy = pd.read_excel('Energy Indicators.xls',sheet_name='Energy',header=16,skipfooter=38).drop([0]).drop(['Unnamed: 1','Unnamed: 0'],axis=1)
Energy = Energy.rename(columns={'Unnamed: 2':'Country','Renewable Electricity Production':'% Renewable'})
Energy=Energy.replace(r'\.\.\.', np.nan, regex=True)
def change_name(row):
    if row['Country']== 'Republic of Korea':
        row['Country']= 'South Korea'
    if row['Country']== 'United States of America':
        row['Country']= 'United States'
    if row['Country']== 'United Kingdom of Great Britain and Northern Ireland':
        row['Country']= 'United Kingdom'
    if row['Country']== 'China, Hong Kong Special Administrative Region':
        row['Country']= 'Hong Kong'
    return row
Energy['Energy Supply']=Energy.apply(lambda x:x['Energy Supply']*1000000,axis='columns')
Energy = Energy.replace(r'(\s\(.*?\))|(\d)',value='',regex=True)
Energy = Energy.apply(change_name,axis='columns')
GDP = pd.read_csv('world_bank.csv',header=4)
def change_name2(row):
    if row['Country Name']== 'Korea, Rep.':
        row['Country Name']= 'South Korea'
    if row['Country Name']=='Iran, Islamic Rep.':
        row['Country Name']= 'Iran'
    if row['Country Name']== 'Hong Kong SAR, China':
        row['Country Name']= 'Hong Kong'
    return row

GDP = GDP.apply(change_name2, axis='columns')
ScimEn = pd.read_excel('scimagojr-3.xlsx')
ScimEn = ScimEn.iloc[0:15]
merge1 = pd.merge(ScimEn,Energy, how='inner',on='Country')
years = ['Country Name','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
GDP = GDP[years]
#DataFrame = pd.merge(merge1,GDP,how='inner',left_index=True,right_index=True)

In [3]:
merge1

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,% Renewable
0,1,China,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910
1,2,United States,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980
2,3,Japan,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820
3,4,United Kingdom,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470
4,5,Russian Federation,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680
5,6,Canada,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430
6,7,Germany,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530
7,8,India,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080
8,9,France,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280
9,10,South Korea,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353
10,11,Italy,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230
11,12,Spain,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590
12,13,Iran,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721
13,14,Australia,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810
14,15,Brazil,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030

In [4]:
merge1.set_index('Country')

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,% Renewable
Country,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030

In [5]:

GDP.rename(columns={'Country Name':'Country'},inplace=True)
GDP.set_index('Country')

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,
Aruba,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
Andorra,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
Afghanistan,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
Angola,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
Albania,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
...,...,...,...,...,...,...,...,...,...,...
"Yemen, Rep.",2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
South Africa,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
"Congo, Dem. Rep.",1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
Zambia,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
Zimbabwe,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [6]:
DataFrame = pd.merge(merge1,GDP).set_index('Country')

In [7]:
DataFrame

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [8]:
years2 = ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']

In [9]:
#my_categories = pd.CategoricalDtype(ordered=True)

avgGDP = DataFrame[years2].mean(axis=1)

In [10]:
avgGDP

Country
China                 6.348609e+12
United States         1.536434e+13
Japan                 5.542208e+12
United Kingdom        2.487907e+12
Russian Federation    1.565459e+12
Canada                1.660647e+12
Germany               3.493025e+12
India                 1.769297e+12
France                2.681725e+12
South Korea           1.106715e+12
Italy                 2.120175e+12
Spain                 1.418078e+12
Iran                  4.441558e+11
Australia             1.164043e+12
Brazil                2.189794e+12
dtype: float64

In [11]:
avgGDP.sort_values(ascending=False,inplace=True)

In [12]:
avgGDP

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
dtype: float64

In [13]:
rate6thGDP = DataFrame['2015'].iloc[3]/DataFrame['2006'].iloc[3]

In [14]:
rate6thGDP

1.1019588220774517

In [15]:
mean_energy_per_capita = DataFrame['Energy Supply per capita'].mean()

In [16]:
mean_energy_per_capita

157.6

In [17]:
max_RenPer = (DataFrame['% Renewable'].idxmax(axis=0, skipna=True),DataFrame['% Renewable'].max())

max_RenPer

In [18]:
max_RenPer

('Brazil', 69.64803)

In [19]:
#def ratio_column(row):
 #   row['New']= row['Self-Citations']/row['Citations']
  #  return row
#DataFrame.apply(ratio_column)
DataFrame['Ratio citations']= DataFrame['Self-citations']/DataFrame['Citations']

In [20]:
max_Ratio = (DataFrame['Ratio citations'].idxmax(axis=0, skipna=True),DataFrame['Ratio citations'].max())

In [21]:
max_Ratio

('China', 0.6893126179389422)

In [22]:
Est_Population= DataFrame['Energy Supply']/DataFrame['Energy Supply per capita']

In [23]:
Est_Population

Country
China                 1.367645e+09
United States         3.176154e+08
Japan                 1.274094e+08
United Kingdom        6.387097e+07
Russian Federation    1.435000e+08
Canada                3.523986e+07
Germany               8.036970e+07
India                 1.276731e+09
France                6.383735e+07
South Korea           4.980543e+07
Italy                 5.990826e+07
Spain                 4.644340e+07
Iran                  7.707563e+07
Australia             2.331602e+07
Brazil                2.059153e+08
dtype: float64

In [24]:
Est_Population.sort_values(ascending=False,inplace=True)

In [25]:
Est_Population

Country
China                 1.367645e+09
India                 1.276731e+09
United States         3.176154e+08
Brazil                2.059153e+08
Russian Federation    1.435000e+08
Japan                 1.274094e+08
Germany               8.036970e+07
Iran                  7.707563e+07
United Kingdom        6.387097e+07
France                6.383735e+07
Italy                 5.990826e+07
South Korea           4.980543e+07
Spain                 4.644340e+07
Canada                3.523986e+07
Australia             2.331602e+07
dtype: float64

In [26]:
Est_P3th = Est_Population.index[2]

In [27]:
Est_P3th

'United States'

In [26]:
DataFrame['Est Population']= Est_Population

In [27]:
DataFrame

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,Ratio citations,Est Population
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,...,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,...,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,3.176154e+08
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,...,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,1.274094e+08
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,...,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,6.387097e+07
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,...,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,1.435000e+08
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,...,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,3.523986e+07
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,...,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,8.036970e+07
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,...,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,...,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,6.383735e+07
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,...,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,4.980543e+07
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,...,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,5.990826e+07
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,...,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,4.644340e+07
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,...,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,7.707563e+07
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,...,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,2.331602e+07
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,...,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,2.059153e+08

In [28]:
DataFrame['Citable Docs per capita']=DataFrame['Est Population']/DataFrame['Citable documents']

In [29]:
DataFrame

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,% Renewable,...,2009,2010,2011,2012,2013,2014,2015,Ratio citations,Est Population,Citable Docs per capita
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09,10788.652893
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,3.176154e+08,3352.247402
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,1.274094e+08,4206.735430
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,6.387097e+07,3137.543240
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,1.435000e+08,7841.101579
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,...,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,3.523986e+07,1999.992331
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,...,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,8.036970e+07,4775.099339
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09,86027.273717
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,...,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,6.383735e+07,4920.785431
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,...,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,4.980543e+07,4177.256552
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,...,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,5.990826e+07,5550.144236
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,...,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,4.644340e+07,4977.855973
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,...,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,7.707563e+07,8739.724487
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,...,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,2.331602e+07,2672.322902
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,...,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,2.059153e+08,23954.775970

In [91]:
corr = DataFrame['Energy Supply per capita'].corr(DataFrame['Citable Docs per capita'])

In [92]:
corr

-0.5838221986852355

In [93]:
DataFrame

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,% Renewable,...,2011,2012,2013,2014,2015,Ratio citations,Est Population,Citable Docs per capita,High Renew,Continent
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.754910,...,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09,10788.652893,1.0,Asia
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,9.083800e+10,286.0,11.570980,...,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,3.176154e+08,3352.247402,0.0,North America
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.232820,...,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,1.274094e+08,4206.735430,0.0,Asia
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7.920000e+09,124.0,10.600470,...,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,6.387097e+07,3137.543240,0.0,Europe
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.288680,...,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,1.435000e+08,7841.101579,1.0,Europe
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,1.043100e+10,296.0,61.945430,...,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,3.523986e+07,1999.992331,1.0,North America
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,1.326100e+10,165.0,17.901530,...,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,8.036970e+07,4775.099339,1.0,Europe
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.969080,...,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09,86027.273717,0.0,Asia
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,1.059700e+10,166.0,17.020280,...,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,6.383735e+07,4920.785431,0.0,Europe
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,1.100700e+10,221.0,2.279353,...,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,4.980543e+07,4177.256552,0.0,Asia
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6.530000e+09,109.0,33.667230,...,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,5.990826e+07,5550.144236,1.0,Europe
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4.923000e+09,106.0,37.968590,...,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,4.644340e+07,4977.855973,1.0,Europe
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,9.172000e+09,119.0,5.707721,...,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,7.707563e+07,8739.724487,0.0,Asia
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5.386000e+09,231.0,11.810810,...,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,2.331602e+07,2672.322902,0.0,Australia
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.648030,...,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,2.059153e+08,23954.775970,1.0,South America

In [31]:
DataFrame['Est Population']/DataFrame['Citable documents']

Country
China                 10788.652893
United States          3352.247402
Japan                  4206.735430
United Kingdom         3137.543240
Russian Federation     7841.101579
Canada                 1999.992331
Germany                4775.099339
India                 86027.273717
France                 4920.785431
South Korea            4177.256552
Italy                  5550.144236
Spain                  4977.855973
Iran                   8739.724487
Australia              2672.322902
Brazil                23954.775970
dtype: float64

In [33]:
DataFrame['Citable Docs per capita'].corr(DataFrame['Energy Supply per capita'])

-0.5838221986852355

In [34]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = DataFrame
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [35]:
def median_Ren(row):
    median = DataFrame['% Renewable'].median()
    if row['% Renewable']> median:
        row['High Renew']= 1
    else:
        row['High Renew']=0
    return row

In [36]:
DataFrame=DataFrame.apply(median_Ren,axis='columns')

In [37]:
HighRenew = DataFrame['High Renew']

In [38]:
HighRenew

Country
China                 1.0
United States         0.0
Japan                 0.0
United Kingdom        0.0
Russian Federation    1.0
Canada                1.0
Germany               1.0
India                 0.0
France                0.0
South Korea           0.0
Italy                 1.0
Spain                 1.0
Iran                  0.0
Australia             0.0
Brazil                1.0
Name: High Renew, dtype: float64

In [39]:
ans10=HighRenew.sort_values(ascending=False)

In [40]:
ans10

Country
Brazil                1.0
Spain                 1.0
Italy                 1.0
Germany               1.0
Canada                1.0
Russian Federation    1.0
China                 1.0
Australia             0.0
Iran                  0.0
South Korea           0.0
France                0.0
India                 0.0
United Kingdom        0.0
Japan                 0.0
United States         0.0
Name: High Renew, dtype: float64

In [47]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
def continent(row):
    row['Continent']=ContinentDict[row.name]
    return row

DataFrame =DataFrame.apply(continent,axis='columns')

In [48]:
ContinentDict['China']

'Asia'

In [49]:
DataFrame

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,% Renewable,...,2011,2012,2013,2014,2015,Ratio citations,Est Population,Citable Docs per capita,High Renew,Continent
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.754910,...,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09,10788.652893,1.0,Asia
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,9.083800e+10,286.0,11.570980,...,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,3.176154e+08,3352.247402,0.0,North America
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.232820,...,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,1.274094e+08,4206.735430,0.0,Asia
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7.920000e+09,124.0,10.600470,...,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,6.387097e+07,3137.543240,0.0,Europe
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.288680,...,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,1.435000e+08,7841.101579,1.0,Europe
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,1.043100e+10,296.0,61.945430,...,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,3.523986e+07,1999.992331,1.0,North America
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,1.326100e+10,165.0,17.901530,...,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,8.036970e+07,4775.099339,1.0,Europe
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.969080,...,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09,86027.273717,0.0,Asia
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,1.059700e+10,166.0,17.020280,...,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,6.383735e+07,4920.785431,0.0,Europe
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,1.100700e+10,221.0,2.279353,...,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,4.980543e+07,4177.256552,0.0,Asia
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6.530000e+09,109.0,33.667230,...,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,5.990826e+07,5550.144236,1.0,Europe
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4.923000e+09,106.0,37.968590,...,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,4.644340e+07,4977.855973,1.0,Europe
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,9.172000e+09,119.0,5.707721,...,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,7.707563e+07,8739.724487,0.0,Asia
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5.386000e+09,231.0,11.810810,...,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,2.331602e+07,2672.322902,0.0,Australia
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.648030,...,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,2.059153e+08,23954.775970,1.0,South America

In [94]:
Continents_Data=DataFrame.groupby("Continent").agg({'Est Population':(np.size,np.sum,np.mean,np.std)})

In [95]:
Continents_Data

              Est Population
                        size           sum          mean           std
Continent
Asia                     5.0  2.898666e+09  5.797333e+08  6.790979e+08
Australia                1.0  2.331602e+07  2.331602e+07           NaN
Europe                   6.0  4.579297e+08  7.632161e+07  3.464767e+07
North America            2.0  3.528552e+08  1.764276e+08  1.996696e+08
South America            1.0  2.059153e+08  2.059153e+08           NaN

In [52]:
DataFrame

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,% Renewable,...,2011,2012,2013,2014,2015,Ratio citations,Est Population,Citable Docs per capita,High Renew,Continent
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.754910,...,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1.367645e+09,10788.652893,1.0,Asia
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,9.083800e+10,286.0,11.570980,...,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,3.176154e+08,3352.247402,0.0,North America
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.232820,...,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,1.274094e+08,4206.735430,0.0,Asia
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7.920000e+09,124.0,10.600470,...,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,6.387097e+07,3137.543240,0.0,Europe
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.288680,...,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,1.435000e+08,7841.101579,1.0,Europe
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,1.043100e+10,296.0,61.945430,...,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,3.523986e+07,1999.992331,1.0,North America
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,1.326100e+10,165.0,17.901530,...,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,8.036970e+07,4775.099339,1.0,Europe
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.969080,...,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1.276731e+09,86027.273717,0.0,Asia
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,1.059700e+10,166.0,17.020280,...,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,6.383735e+07,4920.785431,0.0,Europe
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,1.100700e+10,221.0,2.279353,...,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,4.980543e+07,4177.256552,0.0,Asia
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6.530000e+09,109.0,33.667230,...,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,5.990826e+07,5550.144236,1.0,Europe
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4.923000e+09,106.0,37.968590,...,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,4.644340e+07,4977.855973,1.0,Europe
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,9.172000e+09,119.0,5.707721,...,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,7.707563e+07,8739.724487,0.0,Asia
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5.386000e+09,231.0,11.810810,...,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,2.331602e+07,2672.322902,0.0,Australia
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.648030,...,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,2.059153e+08,23954.775970,1.0,South America

In [53]:
bins=pd.cut(DataFrame['% Renewable'],5)

In [54]:
bins

Country
China                 (15.753, 29.227]
United States          (2.212, 15.753]
Japan                  (2.212, 15.753]
United Kingdom         (2.212, 15.753]
Russian Federation    (15.753, 29.227]
Canada                (56.174, 69.648]
Germany               (15.753, 29.227]
India                  (2.212, 15.753]
France                (15.753, 29.227]
South Korea            (2.212, 15.753]
Italy                 (29.227, 42.701]
Spain                 (29.227, 42.701]
Iran                   (2.212, 15.753]
Australia              (2.212, 15.753]
Brazil                (56.174, 69.648]
Name: % Renewable, dtype: category
Categories (5, interval[float64]): [(2.212, 15.753] < (15.753, 29.227] < (29.227, 42.701] < (42.701, 56.174] < (56.174, 69.648]]

In [72]:
Multi_Data = DataFrame.groupby(['Continent',bins])["% Renewable"].size()

In [56]:


Continents_Ren

NameError: name 'Continents_Ren' is not defined

In [73]:
Multi_Data

Continent      % Renewable
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Australia      (2.212, 15.753]     1
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
               (42.701, 56.174]    0
               (56.174, 69.648]    0
North America  (2.212, 15.753]     1
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    1
South America  (2.212, 15.753]     0
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    1
Name: % Renewable, dtype: int64

In [74]:
Multi_Data.index.names = ('Continent','% Renewable')

In [62]:
Multi_Data

Continent      % Renewable
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Australia      (2.212, 15.753]     1
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
               (42.701, 56.174]    0
               (56.174, 69.648]    0
North America  (2.212, 15.753]     1
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    1
South America  (2.212, 15.753]     0
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    1
Name: % Renewable, dtype: int64

In [75]:
Multi_Data[Multi_Data!=0]

Continent      % Renewable
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
Name: % Renewable, dtype: int64

In [87]:
Final=pd.Series(DataFrame['Est Population']).map('{:,}'.format)

In [88]:
Final

Country
China                 1,367,645,161.2903225
United States          317,615,384.61538464
Japan                  127,409,395.97315437
United Kingdom         63,870,967.741935484
Russian Federation            143,500,000.0
Canada                  35,239,864.86486486
Germany                 80,369,696.96969697
India                 1,276,730,769.2307692
France                  63,837,349.39759036
South Korea            49,805,429.864253394
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Iran                    77,075,630.25210084
Australia              23,316,017.316017315
Brazil                 205,915,254.23728815
Name: Est Population, dtype: object

In [89]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [1]:
def plot_optional():
    import matplotlib as plt
    %matplotlib inline
    Top15 = answer_one()
    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*Top15['2014']/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(Top15.index):
        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.")